FROM golang:1.6-onbuild
ENV GODEBUG=netdns=1
# FROM ruby:2.3.1
# ADD app/Gemfile app/Gemfile.lock /app/
# WORKDIR /app
# RUN bundle install
# ADD app /app
#
# CMD ["bundle","exec", "unicorn", "-c", "unicorn.conf", "-E", "production"]
